# Generated by Django 6.0.5 on 2026-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(db_index=True, max_length=128)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("enqueued", "Enqueued"),
                            ("admitted", "Admitted"),
                            ("redeemed", "Redeemed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                            ("kill_switch_toggled", "Kill switch toggled"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, default="", max_length=64)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("queue_size", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["room", "created_at"], name="wr_event_room_created"),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="wr_event_type_created",
                    ),
                ],
            },
        ),
    ]
