# Generated by Django 6.1.1 on 2026-09-25 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("waiting_room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomStatus",
            fields=[],
            options={
                "verbose_name": "Room status",
                "verbose_name_plural": "Room status",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("waiting_room.admissionevent",),
        ),
    ]
